### ISSUE TITLE
I get text with ENV when I have finished an edit

### ISSUE THREAD

**Issue by michaelbrusegard** [saecki/live-rename.nvim#4]
https://github.com/user-attachments/assets/252e57dc-ca12-401f-8404-876aad9a2a0e

I attached a video that shows the problem, it was a little hard to explain. I think the issue is related to using brackets or quotes. Maybe it has something to do with mini.bracketed which inserts the second bracket or quote automatically.

**Comment by saecki** [comment]
What happens if you use `vim.lsp.buf.rename()`?

**Comment by michaelbrusegard** [comment]
If I use vim.lsp.buf.rename() it works as expected (but the plugin doesnt trigger ofc).
here is how my keybind command looks:
`vim.keymap.set("n", "crn", "<cmd>lua require('live-rename').rename()<cr>", { desc = "Rename", buffer = event.buf, silent = true })`

**Comment by saecki** [comment]
The `_ENV[...]` seems to be coming from lua_ls when renaming a global, and the new name isn't a valid plain identifier: https://github.com/LuaLS/lua-language-server/blob/d702a55715df19a219e963da496e6fb76db0aacd/script/core/rename.lua#L136
Are you sure that `vim.lsp.buf.rename()` behaves differently?

**Comment by michaelbrusegard** [comment]
You cant see the rename popup in the video, but this is it working with vim.lsp.buf.rename.

https://github.com/user-attachments/assets/063a749d-84a1-40c4-9cbc-ec20e20c616a

**Comment by saecki** [comment]
I don't see you renaming a global in that video. When renaming a local variable, lua_ls won't insert `_ENV[...]`. This plugin will call the exact same handler as `vim.lsp.buf.rename()`, to apply the edits.

If you try to rename the same variable, under the exact same circumstances, once with this plugin and once with `vim.lsp.buf.rename()`, are you getting different results?

**Comment by michaelbrusegard** [comment]
Yes, I do. I have tested many times and swapped between them (Sorry for the bad video). But the issue only happens when i use brackets or quotes inside what I am renaming. (it works as expected with vim.lsp.buf.rename

**Comment by saecki** [comment]
As far as I can tell you don't want the `_ENV[...]` inserted right? But that is intentionally done from lua_ls, because you're renaming a global variable to something that can't be represented by a plain identifier. So it works around that by indexing the global environment using `_ENV[<key>]` with the new quoted and escaped identifier. I can only do so for global variables, because there is no such scope for local variables. In that case lua_ls does what I consider to be wrong and just allows whatever text is put there by the user and inserts it at every reference position (as shown in your second video). I and most other language servers would consider that input to be invalid and report an error instead.

Or in other words, both videos you've sent show a different, but the respectively expected result.

Leaving all that aside, this plugin doesn't interfere in the text editing process and just delegates everything to the handlers defined insdie the client or the default handlers. So unless you can give me a video where I can clearly see that you're getting different results using this plugins `require("live-rename").rename()` and `vim.lsp.buf.rename()`, or provide an example document where I can reproduce the behavior, I can't do anything.

**Comment by michaelbrusegard** [comment]
@saecki You are correct, I did some more testing and encountered the same. Thank you for the explanation and sorry for wasting your time
